from handlers.music_commands import register_music_commands
from handlers.basic_commands import register_basic_commands
from handlers.playlist_commands import register_playlist_commands
from handlers.admin_commands import register_admin_commands
from handlers.spotify_commands import register_spotify_commands